--
- name: server-temp-check
  hosts: dejncc01nov061
  gather_facts: no
  become: yes

  tasks:
  - name: server system-manufacture check
    shell: dmidecode -s system-manufacturer
    register: vendor
  - debug:
      var: vendor.stdout

  - name: HP server ipmi temp
    shell: |
      ipmitool sdr type temp | awk '($1=="15-Front") { print $10 " " $12 }'
      sleep 1
    register: output1
    when: vendor.stdout == 'HPE'
  - debug:
      var: output1.stdout

  - name: Dell server ipmi temp
    shell: |
      ipmitool sdr type temp | awk '($1=="Inlet") { print $10 " " $12 }'
      sleep 1
    register: output1
    when: vendor.stdout != 'HPE'

  - debug:
      var: output1.stdout

  - name: copy the output to a local file
    lineinfile:
      line: "{{inventory_hostname}},Temp={{output1.stdout|join('\n')}}"
      path: "/etc/ansible/result/nova/auth-temp.csv"
      create: yes
    delegate_to: localhost
...
