---
- name: server-temp-check
  hosts: dejn-server-temp
  gather_facts: no
  become: yes
  tasks:
  - name: server system-manufacture check
    shell: dmidecode -s system-manufacturer
    register: vendor
  - name: server ipmi temp
    shell: |
      ipmitool sdr type temp | awk -F '*[|]*' '($1=="01-Inlet Ambient") { print $2 }' 
      sleep 5
    register: output1
  - when: {{ vendor }} == 'HPE'

  - name: server ipmi temp
    shell: |
      ipmitool sdr type temp | awk -F '*[|]*' '($1=="15-Front Ambient") { print $2 }' 
      sleep 5
    register: output1
  - when: {{ vendor }} != 'HPE'  

  - name: copy the output to a local file
    lineinfile:
      line: "{{inventory_hostname}},"Temp="{{output1.stdout}}}"
      path: "/etc/ansible/result/nova/auth-temp.csv"
      create: yes
    delegate_to: localhost
...
